if(EXISTS "/home/runner/work/pp-ledger/pp-ledger/_codeql_build_dir/lib/test/test_module[1]_tests.cmake")
  include("/home/runner/work/pp-ledger/pp-ledger/_codeql_build_dir/lib/test/test_module[1]_tests.cmake")
else()
  add_test(test_module_NOT_BUILT test_module_NOT_BUILT)
endif()
