if(EXISTS "/home/runner/work/pp-ledger/pp-ledger/_codeql_build_dir/ledger/test/test_dirdirstore[1]_tests.cmake")
  include("/home/runner/work/pp-ledger/pp-ledger/_codeql_build_dir/ledger/test/test_dirdirstore[1]_tests.cmake")
else()
  add_test(test_dirdirstore_NOT_BUILT test_dirdirstore_NOT_BUILT)
endif()
